"""
Generates a single multi-page PDF report: spectrum chart + summary stats +
detected features table. Uses matplotlib's PdfPages so no extra
dependency (like reportlab/fpdf) is required.
"""

from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.figure import Figure


def export_report_pdf(path, wavelengths, noisy_spec, recovered_spec,
                       unc_lower, unc_upper, source_label,
                       rmse_before=None, rmse_after=None, recovery_pct=None, features_rows=None,
                       colors=None, mae_val=None, reference_spec=None):
    """
    features_rows: list of (molecule, wavelength, status, confidence) tuples.
    colors: dict with keys navy, blue_accent, gray_line, text_sub.
    """
    navy = colors["navy"]
    blue = colors["blue_accent"]
    gray = colors["gray_line"]
    text_sub = colors["text_sub"]

    with PdfPages(path) as pdf:
        # ---- Page 1: chart + headline stats ----
        fig = Figure(figsize=(8.5, 11), dpi=150)
        ax_chart = fig.add_axes([0.1, 0.45, 0.85, 0.45])
        if reference_spec:
            ax_chart.plot(wavelengths, reference_spec, color=text_sub, linewidth=1,
                          linestyle=":", label="Reference / Ground Truth")
        ax_chart.plot(wavelengths, noisy_spec, color=gray, linewidth=1,
                      linestyle="--", marker="o", markersize=1.5, label="Observed (Noisy)")
        if recovered_spec:
            ax_chart.fill_between(wavelengths, unc_lower, unc_upper, color=blue,
                                   alpha=0.18, label="Uncertainty (±1σ)")
            ax_chart.plot(wavelengths, recovered_spec, color=navy, linewidth=1.8,
                          label="AI Recovered")
        ax_chart.set_xlabel("Wavelength (nm)")
        ax_chart.set_ylabel("Normalized Flux")
        ax_chart.set_title(f"OurionSpectra Spectrum Report — {source_label}", fontsize=12, color=navy)
        ax_chart.legend(fontsize=8, loc="lower right")
        ax_chart.grid(alpha=0.15)

        fig.text(0.1, 0.36, "Summary Statistics", fontsize=13, weight="bold", color=navy)
        stats_lines = []
        if rmse_before is not None:
            stats_lines.append(f"RMSE Before Recovery:  {rmse_before:.4f}")
        if rmse_after is not None:
            stats_lines.append(f"RMSE After Recovery:   {rmse_after:.4f}")
        if mae_val is not None:
            stats_lines.append(f"MAE:                   {mae_val:.4f}")
        if recovery_pct is not None:
            stats_lines.append(f"Recovery Improvement:  {recovery_pct:.1f}%")
        stats_lines.append(f"Data Points:           {len(wavelengths)}")
        stats_text = "\n".join(stats_lines) + "\n"
        fig.text(0.1, 0.20, stats_text, fontsize=10, family="monospace", va="top", color="black")
        fig.text(0.1, 0.05,
                 "Generated by OurionSpectra. AI-assisted predictions, not confirmed scientific detections.",
                 fontsize=7, color=text_sub, style="italic")
        pdf.savefig(fig)

        # ---- Page 2: detected features table ----
        fig2 = Figure(figsize=(8.5, 11), dpi=150)
        fig2.text(0.1, 0.92, "Detected Atmospheric Features", fontsize=13, weight="bold", color=navy)
        ax_table = fig2.add_axes([0.08, 0.55, 0.85, 0.3])
        ax_table.axis("off")
        if features_rows:
            table = ax_table.table(
                cellText=features_rows,
                colLabels=["Molecule", "Wavelength", "Status", "AI Confidence"],
                loc="center", cellLoc="left",
            )
            table.auto_set_font_size(False)
            table.set_fontsize(9)
            table.scale(1, 1.6)
        else:
            fig2.text(0.1, 0.7, "No features available — run recovery first.", fontsize=10)
        pdf.savefig(fig2)
